#!/bin/sh
flag1="-s"
flag2="-l"
value=`cat /home/thatguy/.myscripts/git-manage/config.txt`
if [ -n "$1" ];then
	if [ "$1" = "$flag1" ];then
		echo "$2" > /home/thatguy/.myscripts/git-manage/config.txt
	elif [ "$1" = "$flag2" ];then
		echo "$value"
	fi
else
x=`git checkout -f "$value"`
fi
